### ISSUE TITLE
USER STORY:  New account registration

### ISSUE THREAD

**Issue by gStarhigh** [gStarhigh/pro4#1]
As a **Site User** I can **register for an account** so that **I can book, update and delete my bookings**

**EPIC:** User Authorization.

**Acceptance Criteria:**

A: A signup button should be visible when not logged in on all pages.
B: When signup button is clicked I should be taken to the login page.
C: When I fill in my details and submit my account should be created.
D:  I should be notified when I have been successfully logged in.

**Tasks:**
- [x] Install allauth and add to installed apps
- [x] Add allauth urls
- [x] Add signup link to navbar
- [x] Create message to notify user of successfull signup

**Comment by gStarhigh** [comment]
Having issue with the success message as it shows 2 messages at once, both that I've logged out and in.

**Comment by gStarhigh** [comment]
Message to notify the user has now been completed.
