### ISSUE TITLE
USER STORY: Create "Contact us" page

### ISSUE THREAD

**Issue by gStarhigh** [gStarhigh/pro4#10]
As a **user** I can **contact the teacher** so that **I can get answers to my questions**
****
**EPIC:** Contact Abilities.

**Acceptance Criteria:**

A: As a User I should be able to fill out a form that I can use to contact the teacher to get answers to my questions.
B: As a User I should get a success message when the form has been submitted.

**Tasks:**

- [x] Create a contact form template.
- [x] Create the form for the user to submit,
- [x] Create the emailJS so that the teacher gets an email when the form has been submitted.
- [x] Create the success message for the user.

**Comment by gStarhigh** [comment]
Contact form created. Pre-populated fields are Name and Email, if the user is authenticated. 
The form, view, url and contact.html has all been created, however more code and styling is needed.

**Comment by gStarhigh** [comment]
Email JS has successfully been implemented.

**Comment by gStarhigh** [comment]
Successmessage has succesfully been implemented.

**Comment by gStarhigh** [comment]
User Story completed.
