### ISSUE TITLE
USER STORY: Add or update user information

### ISSUE THREAD

**Issue by gStarhigh** [gStarhigh/pro4#14]
As a **User** I can **see my account information** so that **I can add first name, lastname, update email adress**
****
**EPIC:** User Authorization.

**Acceptance Criteria:** 

A: The user can see their saved information on a account page.
B: The user can add information to their account page.
C: The user can update information on their account page.
D: The user can delete information from their account page.

**Tasks:** 

- [x] Create the account view, form, url and html page.
- [x] Update base.html with the new dropdown option.
- [x] Show messages to the user depending on what they do.

**Comment by gStarhigh** [comment]
Created the view, url and HTML page. Form is not needed as it excists withing allauth

**Comment by gStarhigh** [comment]
Added link to the details page from the navbar

**Comment by gStarhigh** [comment]
Messages shown depending on what the user updates. If the user updates more than 1, it will be displayed in a list, one after the other.

**Comment by gStarhigh** [comment]
Site validated. All criteria met.
