### ISSUE TITLE
USER STORY: Admin panel

### ISSUE THREAD

**Issue by gStarhigh** [gStarhigh/pro4#15]
As a **Admin** I can **approve lessons** so that **the user can see that it has been approved**

**EPIC**: Admin

**Acceptance Criteria:**

A: When A user creates a booking the Admin receives an email about it.
B: Admin can approve lessons.
C: Admin can filter in the admin panel on approved/ awaiting approval lessons.
D: Admin can filter by date and/or time.
E: When the lesson is approved, status should change for both admin and user from Awaiting approval to Approved.

**Tasks:**

- [x] Set up the admin panel. 
- [x] Set up the filtering.
- [x] Set up the approval logic.
