### ISSUE TITLE
USER STORY: View my bookings

### ISSUE THREAD

**Issue by gStarhigh** [gStarhigh/pro4#3]
As a **logged in user** I can **see all my bookings** so that **I know when I my bookings will take place**

****

**EPIC:** Lesson Booking.

**Acceptance Criteria:**

A: When the user is logged in, a "My Bookings" button should appear in the Navbar.
B: When the user clicks "My Bookings" the user should be taken to the "My Bookings page"
C: On the "My Bookings" page, all the users bookings should be listed.
D: The Status of each booking should be visible to the user.

**Tasks:**

- [x] Create HTML template for my bookings.
- [x] Create a user friendly card layout of each booking to make it easy to see.
- [x] Create a button for "My Bookings" on the Navbar that only shows if the user is logged in.
- [x] Create a view for "My Bookings" with Django and filter only the bookings made by the logged in user.

**Comment by gStarhigh** [comment]
The view for the bookings is complete. However more styling will be applied.

**Comment by gStarhigh** [comment]
I wanted to add a email that informs the user when the booking has been approved, however emailJS only allows for 2 templates, So this might be a future implementation.
