### ISSUE TITLE
USER STORY: Update and delete Bookings

### ISSUE THREAD

**Issue by gStarhigh** [gStarhigh/pro4#4]
As a **Logged In Site User** I can **update and delete my bookings** so that **I can change or cancel my bookings.**
****

**EPIC:** Lesson Booking.

**Acceptance Criteria:**

A: If the user is logged in and is the creator of the Booking, the user can Edit their booking.
B:  If the user clicks "edit" and it is more than 24hours until the booked time, they should be taken to the edit booking form and it should be populated with the original booking information.
C: If the user tries to edit or cancel their booking within 24hours of the booked time, it should display an error and information to the user that they cannot alter their booking.
D: If the user tries to delete their booking with more than 24 hours to the booked time, the user should receive a warning asking if they are sure that they want to delete their booked time.
E: The user should see a success message if the update or delete booking was successfull.
F: If the User updated their booking successfully, the updated booking should be visible under "My Bookings".
G: If the user deleted their booking successfully, the booking should no longer vi visible under "My Bookings".

**Tasks:**

- [x] Create UpdateBooking and DeleteBooking in views.py.
- [x]  Validation - Ensure user is logged in and the creator of the booking before they can edit or delete the booking.
- [x] Validation - Check if there is more or less than 24hours until the booked time.
- [x] Create update/delete buttons for the bookings.

**Comment by gStarhigh** [comment]
Delete function in place and works as it should.

**Comment by gStarhigh** [comment]
Message to notify the user has now been completed.

**Comment by gStarhigh** [comment]
Fixed so you can no longer delete a lesson if there is less than 24 hours until it starts. You can however still update and change date and time.

**Comment by gStarhigh** [comment]
Acceptance Criteria C: I decided to allow updates to bookings that are within 24 hours, however deletion of the booking is not allowed within 24 hours.
