### ISSUE TITLE
USER STORY: Create a new booking

### ISSUE THREAD

**Issue by gStarhigh** [gStarhigh/pro4#5]
As a **logged in user** I can **create a booking** so that **it appears under "My Bookings"**
****
**EPIC:** Lesson Booking.

**Acceptance Criteria:**

A: As a logged in User, I can choose from specific times and dates that are available and book that lesson.
B: As a logged in User, I can book up to 3 participants on each available time if no one else has booked that time.
C: As a logged in User, I can see if the time and date are available to book.
D: As a logged in User, I cannot book any date or time that has passed.

**Tasks:**

- [x] Validation - Check so that the date and times are available, Max 3 participants per lesson.
- [x] Validation - Check so that the date and time have not passed
- [x] Validation - Check so that the user is Logged in, and if not, do not display the create booking button.
- [x] Create template for NewBooking
- [x] Create DateBooking in views.py
- [x] Create the date/time view and buttons for the booking.

**Comment by gStarhigh** [comment]
the templates name is create_booking, not newbooking

**Comment by gStarhigh** [comment]
Message to notify the user has now been completed.

**Comment by gStarhigh** [comment]
Added emailJS function that sends an email with the lesson details to the site owner.

**Comment by gStarhigh** [comment]
Criteria C: As a logged in User, I can see if the time and date are available to book.
C - This one is partially solved, if the booking time is full, you will get an message. If it's not full, the booking will be accepted.
I believe an AJAX request to the server would solve this. Will not be implemented for this project
