### ISSUE TITLE
USER STORY: Add information to my booking

### ISSUE THREAD

**Issue by gStarhigh** [gStarhigh/pro4#6]
As a **Logged in User** I can **add information to my booking** so that **the teacher can be prepared for the lesson**
****
**EPIC:** Lesson Booking.

**Acceptance Criteria:**

A: If the logged in User has chosen a date and time that is available, they should be taken to the BookingDetails page.
B: The user should be able to choose the number of participants from a dropdown list.
C: The user should be able to choose the level of the ekipage from a dropdown list.
D: The user should be able to enter additional information in a text area to be submitted to the teacher.
E: The user should be able to both cancel and confirm the booking.
F: Success messages should be visible for the user after either canceling or confirming the booking.

**Tasks:**

- [x] Create BookingDetails in views.py
- [x] Create Cancel and Confirm buttons.
- [x] Create BookingDetails template.
- [x] Create success messages for successfull cancelation or confirmation booking.

**Comment by gStarhigh** [comment]
All tasks have been completed where the success messages were the last to be finished.
