### ISSUE TITLE
USER STORY: Create Homepage

### ISSUE THREAD

**Issue by gStarhigh** [gStarhigh/pro4#8]
As a **user** I can **immediately understand the purpose of the site** so that **I can easily decide if it meets my needs.**
****
**EPIC:** Home/About pages

**Acceptance Criteria:**

A: The purpose of the site should be immediately obvious for the user.
B: If the user is not logged in, there should be a modal at the top of the site to encourage the user to login or create an account.

**Tasks:**

- [x] Create the base template and the index.html template.
- [x] Make the sites purpose obvious to the user.
- [x] Make the site responsive and easy to navigate for the user.

**Comment by gStarhigh** [comment]
Created and all Tasks has been completed.
